name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Write cookies file
        run: echo "$YT_COOKIES" > cookies.txt
        env:
          YT_COOKIES: ${{ secrets.YT_COOKIES }}

      - name: Run yt-dlp script
        run: python app.py
